---
language: php

matrix:
  include:
    - env: TEST="API"
      php: 7
    - env: TEST="API"
      php: 5.6
    - env: TEST="EMBER"
    - env: TEST="BROWSER"

dist: trusty
sudo: false

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    - "BROWSERSTACK_USERNAME=jeldrikhanschke1"
    - "BROWSERSTACK_ACCESS_KEY=xaM9Uxurv2GyxFLKQXgj"

before_install:
  # provide yarn if ember build is tested
  - if [ $TEST = "EMBER" ] || [ $TEST = "BROWSER" ]; then curl -o- -L https://yarnpkg.com/install.sh | bash; fi
  - if [ $TEST = "EMBER" ] || [ $TEST = "BROWSER" ]; then export PATH=$HOME/.yarn/bin:$PATH; fi

install:
  # install dependencies for client
  - if [ $TEST = "EMBER" ] || [ $TEST = "BROWSER" ]; then yarn install --no-interactive; fi
  # install dependencies for api
  - if [ $TEST = "API" ]; then cd api/ && composer install && cd ..; fi

before_script:
  # http://php.net/manual/de/ini.core.php#ini.always-populate-raw-post-data
  - if [ $TEST = "API" ]; then echo 'always_populate_raw_post_data = -1' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  # create a browser stack tunnel for cross-browser testing
  - if [ $TEST = "BROWSER" ]; then node_modules/ember-cli/bin/ember browserstack:connect; fi

script:
  # run frontend and integration tests
  - if [ $TEST = "EMBER" ]; then yarn run lint:hbs; fi
  - if [ $TEST = "EMBER" ]; then yarn run lint:js; fi
  - if [ $TEST = "EMBER" ]; then yarn test; fi
  # test against different browsers using sauce lab
  - if [ $TEST = "BROWSER" ]; then yarn test --config-file testem.browserstack.js; fi
  # run api tests with composer
  - if [ $TEST = "API" ]; then cd api/ && ./vendor/bin/codecept run && cd ..; fi

after_script:
  # destroy the sauce tunnel
  - if [ $TEST = "BROWSER" ]; then node_modules/ember-cli/bin/ember browserstack:disconnect; fi
